---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
spec:
  volumes:
  - name: storage
    hostPath:
      path: /mnt/minikube
      type: Directory
  containers:
  - name: kafka-consumer
    image: docker.io/bitnami/kafka:3.4.0-debian-11-r28
    command:
      - kafka-console-consumer.sh
      - --topic
      - demo-topic
      - --bootstrap-server
      ## Instruct your client to connect to the ockam sidecar
      - localhost:9092
  - name: sidecar
    ## For local-built images
    image: ockam-kafka-sidecar:latest
    imagePullPolicy: Never
    ## For GHCR images
    # image: ghcr.io/build-trust/ockam-kafka-sidecar:latest
    env:
    - name: ROLE
      value: consumer
    - name: BOOTSTRAP_SERVER
      value: 127.0.0.1:9092
    - name: OUTLET_HOST
      value: kafka-outlet
    - name: OUTLET_PORT
      value: "6000"
    - name: ENROLL_TOKEN
      value: /mnt/storage/consumer.token
    - name: OCKAM_CONTROLLER_IDENTITY_ID
      value: "Pd14c9e0a57cd41382c69092987cc7ce912a8f7ec7de26cd44115a42561b1a4de"
    - name: OCKAM_HOME
      value: "/mnt/storage/ockam_home/consumer"
    - name: OCKAM_DISABLE_UPGRADE_CHECK
      value: "1"
    volumeMounts:
      ## Provision project info json file via volume mount
      - name: storage
        mountPath: /mnt/storage
        readOnly: false


