---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-outlet
  labels:
    app.kubernetes.io/name: kafka-outlet
spec:
  volumes:
  - name: storage
    hostPath:
      path: /mnt/minikube
      type: Directory
  containers:
  - name: sidecar
    ## For local-built images
    image: ockam-kafka-sidecar:latest
    imagePullPolicy: Never
    ## For GHCR images
    # image: ghcr.io/build-trust/ockam-kafka-sidecar:latest
    env:
    - name: ROLE
      value: outlet
    - name: OUTLET_PORT
      value: "6000"
    - name: BOOTSTRAP_SERVER
      value: kafka:9092
    - name: ENROLL_TOKEN
      value: /mnt/storage/outlet.token
    - name: OCKAM_CONTROLLER_IDENTITY_ID
      value: "Pd14c9e0a57cd41382c69092987cc7ce912a8f7ec7de26cd44115a42561b1a4de"
    - name: OCKAM_HOME
      value: "/mnt/storage/ockam_home/outlet"
    - name: OCKAM_DISABLE_UPGRADE_CHECK
      value: "1"
    ports:
    - containerPort: 6000
      name: ockam
      protocol: TCP
    volumeMounts:
      ## Provision project info json file via volume mount
      - name: storage
        mountPath: /mnt/storage
        readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-outlet
spec:
  selector:
    app.kubernetes.io/name: kafka-outlet
  ports:
    - name: ockam
      protocol: TCP
      port: 6000
      targetPort: ockam
